version: "3.3"

services:
  db:
    image: mongo:5
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGODB_DATABASE: portfolios_portfolio
    volumes:
      - ./mongo:/data/db

  app:
    build: .
    restart: always
    ports:
      - "3003:3003"
    environment:
      PORT: 3003
      MONGODB: mongodb://db:27017/portfolios_portfolio
    depends_on:
      - db
