version: "3.3"

services:
  db:
    image: mongo:5
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGODB_DATABASE: portfolios_portfolio
    volumes:
      - ./mongo:/data/db
